### PR TITLE
TFCM.04-Solution-AddFirebaseMessagingService

### PR DESCRIPTION
**Pull request by ahmed56734**

### CODE REVIEW

**Comment by ahmed56734** [comment]
@v-levonyan  I think the event listener for receiving the message is what is done in the background
not  the method  onMessageReceived itself

**Comment by v-levonyan** [comment]
@ahmed56734 hi,
thank's for response. From this [link](https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/FirebaseMessagingService.html#onMessageReceived(com.google.firebase.messaging.RemoteMessage)):

I found the following: Override base class methods to handle any events required by the application. Methods **are invoked** on a background thread.

**Comment by v-levonyan** [comment]
@ahmed56734 hi again :)
even you can check this by inserting this code:
`        if (Looper.getMainLooper().getThread() == Thread.currentThread()) {
            // On UI thread.
            Log.d(LOG_TAG, "On UI thread");
        } else {
            // Not on UI thread.
            Log.d(LOG_TAG, "Not on UI thread");
        }`
in  onMessageReceived body.

**Comment by cetonek** [comment]
I also believe it is run on background thread by default. In the  `FirebaseMessagingService.java` that we extend from , the `onMessageReceived` method is annotated with `@android.support.annotation.WorkerThread` , which I believe suggests, that it is not a UI thread. It would be wierd if it was run on UI thread, because when this code is run, there might not be any UI at all

**Pull request closed without merging**
